### ISSUE TITLE
including mpi.h?

### ISSUE THREAD

**Issue by pstjohn** [conda-forge/mumps-feedstock#6]
when trying to link with IPOPT (conda-forge/staged-recipes#1607), I'm getting errors on not including `mpi.h`. It looks like this is supposed to get included with `mumps`, but the current recipe seems to omit it: http://list.coin-or.org/pipermail/ipopt/2013-June/003410.html

I'll send in a PR to include it, but do we need to worry about conflicting with `mpi.h` from any other packages?

**Comment by basnijholt** [comment]
Thanks for the PR #7 !

I think @jakirkham would know much better than I do, I don't know if he's automatically notified, but now he for sure is :)

**Comment by tkralphs** [comment]
This is a kind of nasty issue that can indeed has caused widespread problems (see, e.g., https://groups.google.com/forum/#!topic/linux.debian.bugs.dist/yA4AZdoe9vM). I just happened to run into it today in a completely independent context. When building one of the COIN projects that actually uses MPI, this causes the compilation to fail. I'm not sure of the proper fix yet, though, since installing the Mumps version of `mpi.h` is required for some compilations and causes others to fail.  The ideal fix would be for the Mumps guys not to include a file named `mpi.h` in their distribution, but I'm sure they are aware of these issues and it hasn't changed yet.

**Comment by pstjohn** [comment]
we could rename and or move `mpi.h` from this recipe (`mumpsmpi.h` or `mumps/mpi.h`) and just make sure we include a patch for subsequent packages that build off it.

I have no idea how easy it would be to merge those changes upstream. We have the advantage that nobody is building off the mpi.h from this recipe yet, so we won't break anything by moving it

**Comment by tkralphs** [comment]
I would be happy to have a general solution/patch for this issue that could also be applied within COIN's ThirdParty build for Mumps. At the moment, there are projects I can't build out of the box because of this issue. If there's an easy solution to it, though, it seems strange that it hasn't just been changed in the Mumps package itself. Let me play around a little and see if I can come up with a patch that addresses the issue. I guess that Debian does have a match that addresses it for their purposes.

**Comment by tkralphs** [comment]
[This patch](https://github.com/coin-or-tools/ThirdParty-Mumps/blob/27d06cfba2375e74c97c75231b061fe1a59cb291/mumps_mpi.patch) seems to do the trick for allowing my stuff to build correctly with Mumps. I tried to do it in a way that I thought would not break Mumps if one wanted to build Mumps itself with MPI, but I have not tested this. I don't see any reason a similar thing wouldn't work for the conda recipe. The patch is for version 4.10, so it might need to be modified for 5.0.

**Comment by pstjohn** [comment]
Thanks @tkralphs! I did something similar in #7, re-wrote the patch for 5.0 and also included moving `mpi.h` to `mumps_mpi.h.` Works locally, lets see how it does on CI.

**Comment by pstjohn** [comment]
This means we'll also have to put in a patch for IPOPT to change
`/src/Algorithm/LinearSolvers/IpMumpsSolverInterface.cpp`, which asks for `mpi.h`

**Comment by basnijholt** [comment]
Great that this is working, @tkralphs and @pstjohn, thanks for improving this recipe!

@minrk could you please merge #7? I am at a conference with almost zero Internet (even sending this email was difficult...)

On Mon, 28 Nov 2016 at 18:06 "Peter St. John"

<
mailto:
> wrote:

a, pre, code, a:link, body { word-wrap: break-word !important; }

This means we'll also have to put in a patch for IPOPT to change

/src/Algorithm/LinearSolvers/IpMumpsSolverInterface.cpp

, which asks for

mpi.h

—

You are receiving this because you commented.

Reply to this email directly,
https://github.com/conda-forge/mumps-feedstock/issues/6#issuecomment-263394188
, or

**Comment by minrk** [comment]
@basnijholt I would, but I'm not a maintainer on this one.

**Comment by pstjohn** [comment]
No worries, you can take your time for the merge!

**Comment by jakirkham** [comment]
Sorry @basnijholt and @pstjohn , I don't really use MPI. So I don't know that I can really advise you on how best to package `mumps` so as not to clash with MPI. Maybe @conda-forge/mpich or @conda-forge/openmpi can advise.

**Comment by basnijholt** [comment]
@minrk got confused with Metis and Scotch :)
